name: Release Lab PDF

on:
  push:
    tags:
      - 'lab*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Typst
        uses: typst-community/setup-typst@v3
      - name: Compile PDF
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Processing tag: $TAG_NAME"

          if [ -d "$TAG_NAME" ]; then
            echo "Compiling $TAG_NAME/report.typ..."

            typst compile --root . "$TAG_NAME/report.typ" "$TAG_NAME/report.pdf"

          else
            echo "Error: Directory $TAG_NAME not found!"
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            */*.pdf
            name: "Report: $GITHUB_REF_NAME"
            generate_release_notes: true
